# Usamos la imagen oficial de LiteLLM. Esta imagen solo se usa para cloud deployments.
FROM ghcr.io/berriai/litellm:main-latest

COPY litellm_config.yaml /app/config.yaml

CMD ["--config", "/app/config.yaml", "--port", "8080", "--detailed_debug"]