# Usamos la imagen oficial de LiteLLM. Esta imagen solo se usa para cloud deployments.
# Usamos la imagen oficial de LiteLLM.
FROM ghcr.io/berriai/litellm:main-latest

# Definimos el argumento (por defecto 'cloud' para evitar fallos si se omite)
ARG ENVIRONMENT=cloud

# Copiamos dinámicamente el yaml correspondiente
COPY src/config/litellm_config.${ENVIRONMENT}.yaml /app/config.yaml

CMD ["--config", "/app/config.yaml", "--port", "8080", "--detailed_debug"]